### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by totolook** [riccardocarbone2016/BoatRESTful#2]
Quando avvio sul progetto mi esce 404 su ../BoatRESTful/boatSe/ready e anche altri endpoint

**Comment by riccardocarbone2016** [comment]
Ho appena verificato ed il servizio funziona correttamente, sia lasciando che sia un'IDE come eclipse a fare il deploy, sia per via diretta esportando un .war . Se stai usando la prima strada, ti consiglio di riconfigurare il server in eclipse, se continui ancora ad avere problemi usa la seconda strada.
